baseurl = "/"
languageCode = "en-US"
title = "Madison Brenner Portfolio"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "portfolioimage.jpeg"
  author = "Madison Brenner"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "madisonebrenner@gmail.com"
  LinkedIn      = "https://www.linkedin.com/in/madison-brenner/"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume.pdf"
